### ISSUE TITLE
screenshots of issues on HF demo 

### ISSUE THREAD

**Issue by sammcgrail** [lilacai/lilac#601]
// 1

<img width="1728" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/05ace5cf-6498-4ebe-95e6-3a79cd390281">

hitting trash on legal-termination

`hitting trash on legal-termination
ApiError
message	Internal Server Error
url	POST /api/v1/concepts/{namespace}/{concept_name}
status	500
path	{
  "namespace": "lilac",
  "concept_name": "legal-termination"
}
body	{
  "remove": [
    "811d0dcc92e14c5c881e903c7d4ff7b6"
  ]
}
details	Traceback (most recent call last):
  File "/home/user/app/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/app/lilac/router_concept.py", line 77, in edit_concept
    return DISK_CONCEPT_DB.edit(namespace, concept_name, change, user)
  File "/home/user/app/lilac/concepts/db_concept.py", line 451, in edit
    raise ConceptAuthorizationException(
lilac.auth.ConceptAuthorizationException: Concept "lilac/legal-termination" does not exist or user does not have access.

seems like same ish error slightly diff trace`

// 2

<img width="1728" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/ffac14c6-a703-4269-9b31-30d4ac40b224">

// 3

<img width="1038" alt="Screenshot 2023-08-25 at 4 43 43 PM" src="https://github.com/lilacai/lilac/assets/6109568/3b315cc6-1c97-4fb8-a3a1-d82cd8ee2222">

minor improvement not a bug but the hover could be the whole card, cause it feels weird UX to have it just be the text

// 4 

<img width="1728" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/3f8e28a2-dfe1-4243-86dc-06feabd7d77b">
<img width="1722" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/dceef1da-be5e-4e97-9421-6095dfcf84d6">

`Traceback (most recent call last):
  File "/home/user/app/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/app/lilac/router_concept.py", line 77, in edit_concept
    return DISK_CONCEPT_DB.edit(namespace, concept_name, change, user)
  File "/home/user/app/lilac/concepts/db_concept.py", line 451, in edit
    raise ConceptAuthorizationException(
lilac.auth.ConceptAuthorizationException: Concept "lilac/legal-termination" does not exist or user does not have access.`

// 5 
<img width="1728" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/3e949f13-0ba5-4a4c-8031-7f0b2f8d3180">
if you fill up the text box on lang_detection and show preview, if itgoes off the page the padding or css for the slider button is touching bottom of browser

bottom padding issue

// 6 

<img width="538" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/a66ec829-0bfa-4821-bb94-b030959f6793">

if you apply a filter it will be like 10 of 88,393
but potentially just see the second part if no filters... 

// 7 
<img width="1728" alt="PNG image" src="https://github.com/lilacai/lilac/assets/6109568/ea887f83-fbe2-45c3-ae64-ab3e749c0c92">

seemed to occur when changing "sort by" rapidly... but could not reproduce

**Comment by sammcgrail** [comment]
<img width="1725" alt="Screenshot 2023-08-30 at 2 18 34 PM" src="https://github.com/lilacai/lilac/assets/6109568/ab314ec9-e773-4fe7-af18-24c3708890ab">

https://lilacai-lilac.hf.space/signals#text_statistics

`ApiError
message	Internal Server Error
url	POST /api/v1/signals/compute
status	500
path	undefined
body	{
  "signal": {
    "signal_name": "text_statistics"
  },
  "inputs": [
    ""
  ]
}
details	Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/lilac/signals/text_statistics.py", line 45, in setup
    import spacy
ModuleNotFoundError: No module named 'spacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/router_signal.py", line 81, in compute
    signal.setup()
  File "/home/user/.local/lib/python3.9/site-packages/lilac/signals/text_statistics.py", line 49, in setup
    raise ImportError('Could not import the "spacy" python package. '
ImportError: Could not import the "spacy" python package. Please install it with `pip install spacy`.`

**Comment by sammcgrail** [comment]
![image](https://github.com/lilacai/lilac/assets/6109568/ecc35ee7-39df-4f1f-aa73-a0ddb1a73caa)


https://lilacai-lilac.hf.space/datasets#lilac/databricks-dolly-15k-curated-en&query=%7B%22searches%22%3A%5B%7B%22path%22%3A%5B%22original-context%22%5D%2C%22type%22%3A%22concept%22%2C%22concept_namespace%22%3A%22lilac%22%2C%22concept_name%22%3A%22non-english%22%2C%22embedding%22%3A%22gte-small%22%7D%5D%7D


on this link, I MASHED the ascending vs descending sort button, and eventually got 

`message    Internal Server Error
url    POST /api/v1/datasets/{namespace}/{dataset_name}/select_rows
status    500
path    {
  "namespace": "lilac",
  "dataset_name": "databricks-dolly-15k-curated-en"
}
body    {
  "searches": [
    {
      "path": [
        "original-context"
      ],
      "type": "concept",
      "concept_namespace": "lilac",
      "concept_name": "non-english",
      "embedding": "gte-small"
    }
  ],
  "columns": [
    ""
  ],
  "combine_columns": true,
  "sort_by": [
    [
      "original-context",
      "lilac/non-english/gte-small",
      "",
      "score"
    ]
  ],
  "sort_order": "ASC",
  "limit": 20,
  "offset": 0
}
details    Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, *values)
  File "/home/user/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func,args)
  File "/home/user/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/router_dataset.py", line 230, in select_rows
    res = dataset.select_rows(
  File "/home/user/.local/lib/python3.9/site-packages/lilac/data/dataset_duckdb.py", line 1048, in select_rows
    df[signal_column] = deep_unflatten(signal_out, input)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 51, in deep_unflatten
    return cast(list, _deep_unflatten(iter(flat_input), original_input, is_primitive_predicate))
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 44, in _deep_unflatten
    return [_deep_unflatten(flat_input, orig_elem, is_primitive_predicate) for orig_elem in values]
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 44, in <listcomp>
    return [_deep_unflatten(flat_input, orig_elem, is_primitive_predicate) for orig_elem in values]
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 37, in _deep_unflatten
    return next(flat_input)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/data/dataset_utils.py", line 301, in sparse_to_dense_compute
    out = next(dense_output)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 73, in unflatten
    for original_input in original_inputs:
  File "/home/user/.local/lib/python3.9/site-packages/lilac/embeddings/vector_store.py", line 138, in get
    spans = self._id_to_spans[path_key]
KeyError: ('57d0dd9c82ff4710826a2a8338cbb1d1',)`

**Comment by sammcgrail** [comment]
REPRODUCING PREVIOUS COMMENT  ^^^^^ 

Reproduced here https://lilacai-lilac.hf.space/datasets#lilac/databricks-dolly-15k-curated-en&query=%7B%22searches%22%3A%5B%7B%22path%22%3A%5B%22original-context%22%5D%2C%22type%22%3A%22concept%22%2C%22concept_namespace%22%3A%22lilac%22%2C%22concept_name%22%3A%22non-english%22%2C%22embedding%22%3A%22gte-small%22%7D%5D%2C%22sort_by%22%3A%5B%5B%22original-context%22%2C%22lilac%2Fnon-english%2Fgte-small%22%2C%22*%22%2C%22score%22%5D%5D%2C%22sort_order%22%3A%22ASC%22%7D


ApiError
message	Internal Server Error
url	POST /api/v1/datasets/{namespace}/{dataset_name}/select_rows
status	500
path	{
  "namespace": "lilac",
  "dataset_name": "databricks-dolly-15k-curated-en"
}
body	{
  "searches": [
    {
      "path": [
        "original-context"
      ],
      "type": "concept",
      "concept_namespace": "lilac",
      "concept_name": "non-english",
      "embedding": "gte-small"
    }
  ],
  "columns": [
    "*"
  ],
  "combine_columns": true,
  "sort_by": [
    [
      "original-context",
      "lilac/non-english/gte-small",
      "*",
      "score"
    ]
  ],
  "sort_order": "ASC",
  "limit": 20,
  "offset": 0
}
details	Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/router_dataset.py", line 230, in select_rows
    res = dataset.select_rows(
  File "/home/user/.local/lib/python3.9/site-packages/lilac/data/dataset_duckdb.py", line 1048, in select_rows
    df[signal_column] = deep_unflatten(signal_out, input)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 51, in deep_unflatten
    return cast(list, _deep_unflatten(iter(flat_input), original_input, is_primitive_predicate))
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 44, in _deep_unflatten
    return [_deep_unflatten(flat_input, orig_elem, is_primitive_predicate) for orig_elem in values]
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 44, in <listcomp>
    return [_deep_unflatten(flat_input, orig_elem, is_primitive_predicate) for orig_elem in values]
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 37, in _deep_unflatten
    return next(flat_input)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/data/dataset_utils.py", line 301, in sparse_to_dense_compute
    out = next(dense_output)
  File "/home/user/.local/lib/python3.9/site-packages/lilac/batch_utils.py", line 73, in unflatten
    for original_input in original_inputs:
  File "/home/user/.local/lib/python3.9/site-packages/lilac/embeddings/vector_store.py", line 138, in get
    spans = self._id_to_spans[path_key]
KeyError: ('57d0dd9c82ff4710826a2a8338cbb1d1',)



<img width="1723" alt="Screenshot 2023-08-31 at 2 18 03 PM" src="https://github.com/lilacai/lilac/assets/6109568/bb31da31-cf85-4d60-b2e9-90905da8e433">


I think I selected 
<img width="280" alt="Screenshot 2023-08-31 at 2 18 19 PM" src="https://github.com/lilacai/lilac/assets/6109568/72279ac5-168b-494f-b8a5-0f15a3fd84b1">

This option from dropdown, then scrolled so more rows would be rendered, then mashed asc/desc sort button
