### ISSUE TITLE
Error when trying to apply concept to hello-world Open-Orca example

### ISSUE THREAD

**Issue by hamelsmu** [lilacai/lilac#642]
I am trying to apply the `positive-sentiment` concept to the open-orca dataset, that I loaded while following the getting started example.  I go to the concepts on the left hand side and navigate to "Apply to a Dataset" and select the open-orca dataset I created

![image](https://github.com/lilacai/lilac/assets/1483922/3edc6dde-c2ea-44e7-bc84-7746141b518b)

After doing this I get this error in the app

![image](https://github.com/lilacai/lilac/assets/1483922/bebbfc95-af85-462c-9d78-537cf5d808a4)

```
Traceback (most recent call last): File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/lilac/router_utils.py", line 24, in custom_route_handler return await original_route_handler(request) File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app raw_response = await run_endpoint_function( File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/fastapi/routing.py", line 169, in run_endpoint_function return await run_in_threadpool(dependant.call, **values) File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool return await anyio.to_thread.run_sync(func, *args) File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread return await future File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run result = context.run(func, *args) File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/lilac/router_dataset.py", line 230, in select_rows res = dataset.select_rows( File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/lilac/data/dataset_duckdb.py", line 1050, in select_rows rel = con.from_df(df) duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception: ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

**Comment by chilang** [comment]
Hit the same issue with local install of lilac on a fresh virtual env. 
Downgrading pandas to pre 2.1 fixed it for me `pip install "pandas<2.1"`

**Comment by nsthorat** [comment]
This is an issue with duckdb, I'm going to change our dep on pandas to be 2.0.3 until duckdb is updated: https://github.com/duckdb/duckdb/pull/8738

**Comment by brilee** [comment]
Fixed in https://github.com/lilacai/lilac/pull/731
