### ISSUE TITLE
stream of HTTP 500s after deleting a dataset

### ISSUE THREAD

**Issue by brilee** [lilacai/lilac#830]
We should have some sort of redirect to the dataset index page after deleting a dataset; instead we get a stream of ApiError popup boxes.

raw server logs after deleting a dataset from the UI:
```
INFO:     127.0.0.1:51600 - "DELETE /api/v1/datasets/local/test_jsonl HTTP/1.1" 200 OK
Route error: http://127.0.0.1:5432/api/v1/datasets/local/test_jsonl
Traceback (most recent call last):
  File "/Users/brian/dev/lilac/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/router_dataset.py", line 59, in get_manifest
    dataset = get_dataset(namespace, dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/db_manager.py", line 43, in get_dataset
    _CACHED_DATASETS[cache_key] = _DEFAULT_DATASET_CLS(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 250, in __init__
    self._source_manifest = read_source_manifest(self.dataset_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 2412, in read_source_manifest
    with open_file(os.path.join(dataset_path, MANIFEST_FILENAME), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/utils.py", line 71, in open_file
    return open(filepath, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/local/test_jsonl/manifest.json'

INFO:     127.0.0.1:51608 - "GET /api/v1/datasets/local/test_jsonl HTTP/1.1" 500 Internal Server Error
Route error: http://127.0.0.1:5432/api/v1/datasets/local/test_jsonl/select_rows_schema
Traceback (most recent call last):
  File "/Users/brian/dev/lilac/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/router_dataset.py", line 293, in select_rows_schema
    dataset = get_dataset(namespace, dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/db_manager.py", line 43, in get_dataset
    _CACHED_DATASETS[cache_key] = _DEFAULT_DATASET_CLS(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 250, in __init__
    self._source_manifest = read_source_manifest(self.dataset_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 2412, in read_source_manifest
    with open_file(os.path.join(dataset_path, MANIFEST_FILENAME), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/utils.py", line 71, in open_file
    return open(filepath, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/local/test_jsonl/manifest.json'

INFO:     127.0.0.1:51609 - "POST /api/v1/datasets/local/test_jsonl/select_rows_schema HTTP/1.1" 500 Internal Server Error
Route error: http://127.0.0.1:5432/api/v1/datasets/local/test_jsonl/stats
Traceback (most recent call last):
  File "/Users/brian/dev/lilac/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/router_dataset.py", line 169, in get_stats
    dataset = get_dataset(namespace, dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/db_manager.py", line 43, in get_dataset
    _CACHED_DATASETS[cache_key] = _DEFAULT_DATASET_CLS(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 250, in __init__
    self._source_manifest = read_source_manifest(self.dataset_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 2412, in read_source_manifest
    with open_file(os.path.join(dataset_path, MANIFEST_FILENAME), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/utils.py", line 71, in open_file
    return open(filepath, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/local/test_jsonl/manifest.json'

INFO:     127.0.0.1:51611 - "POST /api/v1/datasets/local/test_jsonl/stats HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:51607 - "GET /api/v1/datasets/ HTTP/1.1" 200 OK
Route error: http://127.0.0.1:5432/api/v1/datasets/local/test_jsonl/select_rows
Traceback (most recent call last):
  File "/Users/brian/dev/lilac/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/router_dataset.py", line 266, in select_rows
    dataset = get_dataset(namespace, dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/db_manager.py", line 43, in get_dataset
    _CACHED_DATASETS[cache_key] = _DEFAULT_DATASET_CLS(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 250, in __init__
    self._source_manifest = read_source_manifest(self.dataset_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 2412, in read_source_manifest
    with open_file(os.path.join(dataset_path, MANIFEST_FILENAME), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/utils.py", line 71, in open_file
    return open(filepath, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/local/test_jsonl/manifest.json'

INFO:     127.0.0.1:51610 - "POST /api/v1/datasets/local/test_jsonl/select_rows HTTP/1.1" 500 Internal Server Error
Route error: http://127.0.0.1:5432/api/v1/datasets/local/test_jsonl/select_rows
Traceback (most recent call last):
  File "/Users/brian/dev/lilac/lilac/router_utils.py", line 24, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/router_dataset.py", line 266, in select_rows
    dataset = get_dataset(namespace, dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/db_manager.py", line 43, in get_dataset
    _CACHED_DATASETS[cache_key] = _DEFAULT_DATASET_CLS(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 250, in __init__
    self._source_manifest = read_source_manifest(self.dataset_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/data/dataset_duckdb.py", line 2412, in read_source_manifest
    with open_file(os.path.join(dataset_path, MANIFEST_FILENAME), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/dev/lilac/lilac/utils.py", line 71, in open_file
    return open(filepath, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/local/test_jsonl/manifest.json'

INFO:     127.0.0.1:51612 - "POST /api/v1/datasets/local/test_jsonl/select_rows HTTP/1.1" 500 Internal Server Error
```

**Comment by brilee** [comment]
supposedly we already do this; perhaps there are background continually-refreshing requests that would need to be cancelled? 
 
https://github.com/lilacai/lilac/blob/76956deb9c35d0c15d8c0fd21fbfec22196be8b2/web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte#L175-L176

**Comment by brilee** [comment]
another possible solution is to return 404s instead of 500s and handle them on the frontend
